# Generated by Django 4.2.30 on 2026-05-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
